#ifndef _DEVICE_REGISTER_H_
#define _DEVICE_REGISTER_H_

#define REGISTER_OPTOCOUPLER_INJECTOR     0x021
#define REGISTER_OPTOCOUPLER_LEVEL        0x022
#define REGISTER_OPTOCOUPLER_VERTICAL     0x024
#define REGISTER_OPTOCOUPLER_MOBILE       0x025

#define REGISTER_I1_MOTOR_DIRECTION       0x001
#define REGISTER_I1_MOTOR_SPEED           0x002
#define REGISTER_I1_MOTOR_PACES_L         0x003
#define REGISTER_I1_MOTOR_PACES_H         0x004
#define REGISTER_I1_MOTOR_PACES_REMAIN_L  0x005
#define REGISTER_I1_MOTOR_PACES_REMAIN_H  0x006
#define REGISTER_I1_MOTOR_HOLD            0x000
#define REGISTER_I1_MOTOR_START           0x000
#define REGISTER_I1_MOTOR_STOP            0x000

#define REGISTER_I2_MOTOR_DIRECTION       0x007
#define REGISTER_I2_MOTOR_SPEED           0x008
#define REGISTER_I2_MOTOR_PACES_L         0x009
#define REGISTER_I2_MOTOR_PACES_H         0x00A
#define REGISTER_I2_MOTOR_PACES_REMAIN_L  0x00B
#define REGISTER_I2_MOTOR_PACES_REMAIN_H  0x00C
#define REGISTER_I2_MOTOR_HOLD            0x000
#define REGISTER_I2_MOTOR_START           0x000
#define REGISTER_I2_MOTOR_STOP            0x000


#define REGISTER_L_MOTOR_DIRECTION        0x041
#define REGISTER_L_MOTOR_SPEED            0x042
#define REGISTER_L_MOTOR_PACES_L          0x043
#define REGISTER_L_MOTOR_PACES_H          0x044
#define REGISTER_L_MOTOR_PACES_REMAIN_L   0x045
#define REGISTER_L_MOTOR_PACES_REMAIN_H   0x046
#define REGISTER_L_MOTOR_HOLD             0x047
#define REGISTER_L_MOTOR_START            0x000
#define REGISTER_L_MOTOR_STOP             0x000

#define REGISTER_V_MOTOR_DIRECTION        0x061
#define REGISTER_V_MOTOR_SPEED            0x062
#define REGISTER_V_MOTOR_PACES_L          0x063
#define REGISTER_V_MOTOR_PACES_H          0x064
#define REGISTER_V_MOTOR_PACES_REMAIN_L   0x065
#define REGISTER_V_MOTOR_PACES_REMAIN_H   0x066
#define REGISTER_V_MOTOR_HOLD             0x067
#define REGISTER_V_MOTOR_START            0x000
#define REGISTER_V_MOTOR_STOP             0x000

#endif

